# Generated by Django 5.2.7 on 2025-12-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_blog_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
