# Generated by Django 5.2.7 on 2025-12-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_award_education_experience_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Optional certificate attachment', null=True, upload_to='education/certificates/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional attachment (e.g., recommendation letter, certificate)', null=True, upload_to='experience/attachments/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date (month and year). Leave blank for current positions', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(help_text='Start date (month and year)'),
        ),
    ]
