# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to leverage Docker cache
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the frontend code into the container
COPY ./frontend /app/

# Expose the port the app runs on
EXPOSE 5173

# Run the application
CMD ["npm", "run", "dev", "--", "--host"]
